```{r}
library(swemaps2)
library(rnaturalearth)
library(stringr)
library(sf)
library(ggplot2)
library(magrittr)

df <- source("fetch_and_tidy_lan_data_api.R", local = TRUE)$value
```

```{r}
df <-
    df %>%
    rename(län = region) %>% 
    full_join(swemaps2::county %>%
                    mutate(län = ln_namn %>% str_c(" län"),
               .keep = 'unused'))
```

```{r}
sf_use_s2(FALSE) # Switch off, otherwise geometry is inverted.

ne_ocean <- rnaturalearth::ne_download(scale = 10,
                            type = 'ocean',
                            category = 'physical',
                            destdir = '.',
                            returnclass = 'sf'
                            )
ne_ocean <- ne_ocean %>% st_make_valid(x) # Required for cropping

## Crop ocean to Swedish surroundings
sea <- ne_ocean %>%
    st_crop(st_bbox(swemaps2::county)  %>% 
                    st_as_sfc()  %>%
                    st_transform(crs = 4326) ) %>%
    st_transform(3006)

sf_use_s2(TRUE) # Reset
```


```{r}
ggplot() +
    geom_sf(data = df, aes(geometry=geometry, fill=median_price) ) +
    geom_sf(data = sea, fill='blue' ) +
    swemaps2::theme_swemap()
```